//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSystem.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegionSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegionSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSystem.Resource.RegionSetting", typeof(RegionSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Management v1.0.
        /// </summary>
        public static string Account_AppName {
            get {
                return ResourceManager.GetString("Account_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display page in:.
        /// </summary>
        public static string Account_DisplayIn {
            get {
                return ResourceManager.GetString("Account_DisplayIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username / Password?.
        /// </summary>
        public static string Account_Forgot {
            get {
                return ResourceManager.GetString("Account_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_LoginButtonCaption {
            get {
                return ResourceManager.GetString("Account_LoginButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not be blank.
        /// </summary>
        public static string Account_PasswordErr {
            get {
                return ResourceManager.GetString("Account_PasswordErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Account_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not valid.
        /// </summary>
        public static string Account_UsernameErr {
            get {
                return ResourceManager.GetString("Account_UsernameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Account_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Account_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Public Holiday.
        /// </summary>
        public static string addPublicHoliday {
            get {
                return ResourceManager.GetString("addPublicHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        public static string Admin_Password {
            get {
                return ResourceManager.GetString("Admin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Application By Admin.
        /// </summary>
        public static string appByAdmin {
            get {
                return ResourceManager.GetString("appByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application was created successfully.
        /// </summary>
        public static string appCreated {
            get {
                return ResourceManager.GetString("appCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed verification.
        /// </summary>
        public static string appFailed {
            get {
                return ResourceManager.GetString("appFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking ref..
        /// </summary>
        public static string appID {
            get {
                return ResourceManager.GetString("appID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string applicantDesc {
            get {
                return ResourceManager.GetString("applicantDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string applicationProgress {
            get {
                return ResourceManager.GetString("applicationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver&apos;s Action.
        /// </summary>
        public static string approverAction {
            get {
                return ResourceManager.GetString("approverAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver&apos;s Comment.
        /// </summary>
        public static string approverDesc {
            get {
                return ResourceManager.GetString("approverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver Username.
        /// </summary>
        public static string approverUserID {
            get {
                return ResourceManager.GetString("approverUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string booleanNo0 {
            get {
                return ResourceManager.GetString("booleanNo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string booleanYes0 {
            get {
                return ResourceManager.GetString("booleanYes0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        public static string Caption_yearlyANNL {
            get {
                return ResourceManager.GetString("Caption_yearlyANNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereavement.
        /// </summary>
        public static string Caption_yearlyBRML {
            get {
                return ResourceManager.GetString("Caption_yearlyBRML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation.
        /// </summary>
        public static string Caption_yearlyCPSL {
            get {
                return ResourceManager.GetString("Caption_yearlyCPSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Marriage.
        /// </summary>
        public static string Caption_yearlyFMRL {
            get {
                return ResourceManager.GetString("Caption_yearlyFMRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick.
        /// </summary>
        public static string Caption_yearlySCKL {
            get {
                return ResourceManager.GetString("Caption_yearlySCKL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Marriage.
        /// </summary>
        public static string Caption_yearlySMRL {
            get {
                return ResourceManager.GetString("Caption_yearlySMRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Caption_yearlySPKL {
            get {
                return ResourceManager.GetString("Caption_yearlySPKL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string Caption_yearlyUPDL {
            get {
                return ResourceManager.GetString("Caption_yearlyUPDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reconfirm new password.
        /// </summary>
        public static string ChangePassword_NewPWNotMatched {
            get {
                return ResourceManager.GetString("ChangePassword_NewPWNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not leave this blank.
        /// </summary>
        public static string ChangePassword_Nonblank {
            get {
                return ResourceManager.GetString("ChangePassword_Nonblank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password change.
        /// </summary>
        public static string ChangePassword_OKbutton {
            get {
                return ResourceManager.GetString("ChangePassword_OKbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is changed. You need to login again..
        /// </summary>
        public static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contain.
        /// </summary>
        public static string contain {
            get {
                return ResourceManager.GetString("contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected date was applied for leave, please terminate related application first.
        /// </summary>
        public static string dateInvalid {
            get {
                return ResourceManager.GetString("dateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string deptName {
            get {
                return ResourceManager.GetString("deptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Details_EditLink_Caption {
            get {
                return ResourceManager.GetString("Details_EditLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string Details_UpdatePasswordLink_Caption {
            get {
                return ResourceManager.GetString("Details_UpdatePasswordLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Change.
        /// </summary>
        public static string Edit_SaveChange_Caption {
            get {
                return ResourceManager.GetString("Edit_SaveChange_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        public static string equal {
            get {
                return ResourceManager.GetString("equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page: .
        /// </summary>
        public static string GotoPage {
            get {
                return ResourceManager.GetString("GotoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Maintenance.
        /// </summary>
        public static string Home_AccMaint {
            get {
                return ResourceManager.GetString("Home_AccMaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Home_AccMaint_Link1 {
            get {
                return ResourceManager.GetString("Home_AccMaint_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Home_Language_Current {
            get {
                return ResourceManager.GetString("Home_Language_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Home_Language_Label {
            get {
                return ResourceManager.GetString("Home_Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit New Application.
        /// </summary>
        public static string Home_LeaveManageLink_Apply {
            get {
                return ResourceManager.GetString("Home_LeaveManageLink_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Leave Application.
        /// </summary>
        public static string Home_LeaveManageLink_Approve {
            get {
                return ResourceManager.GetString("Home_LeaveManageLink_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Management.
        /// </summary>
        public static string Home_LeaveManageLink_Group_Caption {
            get {
                return ResourceManager.GetString("Home_LeaveManageLink_Group_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Leave Balance.
        /// </summary>
        public static string Home_LeaveManageLink_SeeBalance {
            get {
                return ResourceManager.GetString("Home_LeaveManageLink_SeeBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Application.
        /// </summary>
        public static string Home_LeaveManageLink_ShowAll {
            get {
                return ResourceManager.GetString("Home_LeaveManageLink_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Home_Logout_Button_Caption {
            get {
                return ResourceManager.GetString("Home_Logout_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string Home_UserMaint {
            get {
                return ResourceManager.GetString("Home_UserMaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string Home_UserMaint_Link1 {
            get {
                return ResourceManager.GetString("Home_UserMaint_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Overview.
        /// </summary>
        public static string Home_UserMaint_Link2 {
            get {
                return ResourceManager.GetString("Home_UserMaint_Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Quota.
        /// </summary>
        public static string Home_UserMaint_Link3 {
            get {
                return ResourceManager.GetString("Home_UserMaint_Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Home_Welcome_Label {
            get {
                return ResourceManager.GetString("Home_Welcome_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave duration in hrs.
        /// </summary>
        public static string hourRequired {
            get {
                return ResourceManager.GetString("hourRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string initDate {
            get {
                return ResourceManager.GetString("initDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        public static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string leaveBalance {
            get {
                return ResourceManager.GetString("leaveBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Authorization.
        /// </summary>
        public static string leavePending {
            get {
                return ResourceManager.GetString("leavePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota.
        /// </summary>
        public static string leaveQuota {
            get {
                return ResourceManager.GetString("leaveQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string leaveUsed {
            get {
                return ResourceManager.GetString("leaveUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Holiday List.
        /// </summary>
        public static string listPublicHoliday {
            get {
                return ResourceManager.GetString("listPublicHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading_Mask_Content {
            get {
                return ResourceManager.GetString("Loading_Mask_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data not found.
        /// </summary>
        public static string masterDataNotFound {
            get {
                return ResourceManager.GetString("masterDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword_Label {
            get {
                return ResourceManager.GetString("NewPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string NewPasswordConfirm_Label {
            get {
                return ResourceManager.GetString("NewPasswordConfirm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested content is invalid.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not contain.
        /// </summary>
        public static string notContain {
            get {
                return ResourceManager.GetString("notContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal.
        /// </summary>
        public static string notEqual {
            get {
                return ResourceManager.GetString("notEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string nothingFound {
            get {
                return ResourceManager.GetString("nothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now displaying results: .
        /// </summary>
        public static string NowDisplaying {
            get {
                return ResourceManager.GetString("NowDisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword_Label {
            get {
                return ResourceManager.GetString("OldPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Integer Or &lt;Unlimited&gt;.
        /// </summary>
        public static string Quota_Regex {
            get {
                return ResourceManager.GetString("Quota_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string rankDescription {
            get {
                return ResourceManager.GetString("rankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Leaving.
        /// </summary>
        public static string reasonDetail {
            get {
                return ResourceManager.GetString("reasonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Pick a reason --.
        /// </summary>
        public static string reasonDetail_None {
            get {
                return ResourceManager.GetString("reasonDetail_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is disabled.
        /// </summary>
        public static string recordDisabled {
            get {
                return ResourceManager.GetString("recordDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record existed.
        /// </summary>
        public static string recordExists {
            get {
                return ResourceManager.GetString("recordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been inserted successfully.
        /// </summary>
        public static string recordInserted {
            get {
                return ResourceManager.GetString("recordInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a year.
        /// </summary>
        public static string selectYear {
            get {
                return ResourceManager.GetString("selectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string sendRequest {
            get {
                return ResourceManager.GetString("sendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my application.
        /// </summary>
        public static string showMyApp {
            get {
                return ResourceManager.GetString("showMyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting.
        /// </summary>
        public static string systemSetting {
            get {
                return ResourceManager.GetString("systemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string systemStatus {
            get {
                return ResourceManager.GetString("systemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate this application.
        /// </summary>
        public static string terminate {
            get {
                return ResourceManager.GetString("terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        public static string terminated {
            get {
                return ResourceManager.GetString("terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string timeEnd {
            get {
                return ResourceManager.GetString("timeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string timeStart {
            get {
                return ResourceManager.GetString("timeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to access this. Contact admin for more details..
        /// </summary>
        public static string Unauthorized_Alert {
            get {
                return ResourceManager.GetString("Unauthorized_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        public static string unlimited {
            get {
                return ResourceManager.GetString("unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string User_ActiveStatus_Active {
            get {
                return ResourceManager.GetString("User_ActiveStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string User_ActiveStatus_Inactive {
            get {
                return ResourceManager.GetString("User_ActiveStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string User_AddNew_buttonCaption_create {
            get {
                return ResourceManager.GetString("User_AddNew_buttonCaption_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string User_AddNew_fieldCaption_deptCode {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_deptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Status.
        /// </summary>
        public static string User_AddNew_fieldCaption_isuserActive {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_isuserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string User_AddNew_fieldCaption_rankCode {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_rankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string User_AddNew_fieldCaption_userEmail {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_userEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Login Attempts.
        /// </summary>
        public static string User_AddNew_fieldCaption_userFailedLoginAttempt {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_userFailedLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string User_AddNew_fieldCaption_userID {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_AddNew_fieldCaption_userName {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_AddNew_fieldCaption_userPassword {
            get {
                return ResourceManager.GetString("User_AddNew_fieldCaption_userPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User .
        /// </summary>
        public static string User_AddNew_SuccessMessg_param0 {
            get {
                return ResourceManager.GetString("User_AddNew_SuccessMessg_param0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is successfully created!.
        /// </summary>
        public static string User_AddNew_SuccessMessg_param1 {
            get {
                return ResourceManager.GetString("User_AddNew_SuccessMessg_param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address was acquired.
        /// </summary>
        public static string User_AddNew_Unique_userEmail {
            get {
                return ResourceManager.GetString("User_AddNew_Unique_userEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID was acquired.
        /// </summary>
        public static string User_AddNew_Unique_userID {
            get {
                return ResourceManager.GetString("User_AddNew_Unique_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be non-blank.
        /// </summary>
        public static string User_AddNew_Validation_null_deptCode {
            get {
                return ResourceManager.GetString("User_AddNew_Validation_null_deptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be non-blank.
        /// </summary>
        public static string User_AddNew_Validation_null_passWord {
            get {
                return ResourceManager.GetString("User_AddNew_Validation_null_passWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be non-blank.
        /// </summary>
        public static string User_AddNew_Validation_null_rankCode {
            get {
                return ResourceManager.GetString("User_AddNew_Validation_null_rankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be non-blank.
        /// </summary>
        public static string User_AddNew_Validation_null_userEmail {
            get {
                return ResourceManager.GetString("User_AddNew_Validation_null_userEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be non-blank.
        /// </summary>
        public static string User_AddNew_Validation_null_userID {
            get {
                return ResourceManager.GetString("User_AddNew_Validation_null_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be non-blank.
        /// </summary>
        public static string User_AddNew_Validation_null_userName {
            get {
                return ResourceManager.GetString("User_AddNew_Validation_null_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string User_Edit_Common_Invalid {
            get {
                return ResourceManager.GetString("User_Edit_Common_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is acquired.
        /// </summary>
        public static string User_Edit_Email_Accquired {
            get {
                return ResourceManager.GetString("User_Edit_Email_Accquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserID.
        /// </summary>
        public static string User_Edit_Invalid_ID {
            get {
                return ResourceManager.GetString("User_Edit_Invalid_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password of .
        /// </summary>
        public static string User_UpdatePassword_SuccessMessg_param0 {
            get {
                return ResourceManager.GetString("User_UpdatePassword_SuccessMessg_param0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been updated!.
        /// </summary>
        public static string User_UpdatePassword_SuccessMessg_param1 {
            get {
                return ResourceManager.GetString("User_UpdatePassword_SuccessMessg_param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is invalid, please revise ASAP.
        /// </summary>
        public static string validationFailed {
            get {
                return ResourceManager.GetString("validationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is valid, please wait for approval.
        /// </summary>
        public static string validationPassed {
            get {
                return ResourceManager.GetString("validationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string validationStatus {
            get {
                return ResourceManager.GetString("validationStatus", resourceCulture);
            }
        }
    }
}
